server:
  servlet:
    context-path: /pay
  port: 8082
  
spring:
  application:
    name: pay
    consumingSeconds: 10
  profiles:
    active: redis
  datasource:
    url: jdbc:mysql://localhost:3306/distributed?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com.neusoft.pay: DEBUG